<?php

/**
 *
 * Form payment cash 
 *
 * @author Oswaldo Lopez (waldix86@gmail.com)
 */

?>

<?php  $_code= $this->getMethodCode();
       $_model = $this->getMethod();    
       $_getProviders = $_model->getProviders(); 
?>

<ul id="payment_form_<?php  echo $_code ?>" style="display:none;" >       
       <label for="p_method_cpfaster" style="cursor:pointer;">
	       <li>
	       <select id="<?php echo $_code ?>_mes_expiracion"
                        name="payment[store_code]">
                <?php foreach ($_getProviders as $_provider): ?>                	
				    <option value="<?php echo $_provider['internal_name'] ?>"><?php echo $_provider['name'] ?></option>
			    <?php endforeach; ?>
	       </select>
	       </li>
	   </label>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>





